import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Platform, PlatformColor, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { MacroBadges } from "../src/components/MacroBadges";
import { useDataStoreActions, useRecipe } from "../src/data/DataProvider";
import { PORTION_DELTAS, formatPortionLabel, sanitizePortion } from "../src/portion";
import { aggregateRecipeNutrition, duplicateRecipeInput } from "../src/recipes";
const color = (name: string, fallback: string) => Platform.OS === "ios" ? PlatformColor(name) : fallback;
const p = { bg: color("systemGroupedBackground", "#F3F4F6"), card: color("secondarySystemGroupedBackground", "#FFF"), label: color("label", "#111827"), secondary: color("secondaryLabel", "#6B7280"), separator: color("separator", "#E5E7EB"), tint: "#2563EB", danger: "#DC2626" };
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
export default function RecipeEditorScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const id = first(useLocalSearchParams<{ recipeId?: string | string[] }>().recipeId);
  const { data: recipe, isLoading } = useRecipe(id); const { updateRecipe, createRecipe, deleteRecipe } = useDataStoreActions();
  const [name, setName] = useState(""); const [expandedId, setExpandedId] = useState<string | null>(null);
  useEffect(() => { if (recipe) setName(recipe.name); }, [recipe?.id, recipe?.name]);
  if (isLoading) return <View style={s.center}><Text>Loading…</Text></View>;
  if (!recipe) return <View style={s.center}><Text style={s.title}>Recipe not found</Text><Pressable onPress={() => router.back()}><Text style={s.link}>Done</Text></Pressable></View>;
  const updateItems = (items: typeof recipe.items) => void updateRecipe(recipe.id, (current) => ({ name: current.name, createdAt: current.createdAt, items }));
  const commitName = () => { const next = name.trim(); if (!next) return setName(recipe.name); if (next !== recipe.name) void updateRecipe(recipe.id, (current) => ({ name: next, items: current.items, createdAt: current.createdAt })); };
  return <View style={s.screen}><View style={[s.header,{paddingTop:insets.top+8}]}><Text style={s.headerTitle}>Recipe</Text><Pressable onPress={() => router.back()}><Text style={s.done}>Done</Text></Pressable></View><ScrollView contentContainerStyle={[s.content,{paddingBottom:insets.bottom+28}]} keyboardShouldPersistTaps="handled">
    <TextInput accessibilityLabel="Recipe name" value={name} onChangeText={setName} onBlur={commitName} onSubmitEditing={commitName} style={s.nameInput} selectTextOnFocus />
    <View style={s.card}><Text style={s.count}>{recipe.items.length} ingredient{recipe.items.length===1?"":"s"}</Text><MacroBadges nutrition={aggregateRecipeNutrition(recipe.items)}/></View><Text style={s.section}>Ingredients</Text>
    <View style={s.card}>{recipe.items.length ? recipe.items.map((item,index)=><View key={item.id} style={index?s.divider:undefined}><Pressable style={s.itemRow} onPress={()=>setExpandedId(expandedId===item.id?null:item.id)}><View style={s.flex}><Text style={s.itemName}>{item.foodName}</Text><Text style={s.meta}>{formatPortionLabel(item.portion)}{item.brand?` • ${item.brand}`:""}{item.serving?` • ${item.serving}`:""}</Text><MacroBadges nutrition={item.nutrition} multiplier={item.portion}/></View><Ionicons name={expandedId===item.id?"chevron-up":"chevron-down"} size={18} color={p.secondary}/></Pressable>{expandedId===item.id?<View style={s.editor}><View style={s.portions}>{PORTION_DELTAS.map(action=><Pressable key={action.delta} style={s.portionButton} onPress={()=>updateItems(recipe.items.map(candidate=>candidate.id===item.id?{...candidate,portion:sanitizePortion(candidate.portion+action.delta)}:candidate))}><Text style={s.portionText}>{action.label}</Text></Pressable>)}</View><Pressable onPress={()=>updateItems(recipe.items.filter(candidate=>candidate.id!==item.id))}><Text style={s.remove}>Remove</Text></Pressable></View>:null}</View>):<Text style={s.empty}>No ingredients yet.</Text>}</View>
    <Pressable style={s.add} onPress={()=>router.push({pathname:"/log-food",params:{recipeId:recipe.id}})}><Ionicons name="add" size={20} color={p.tint}/><Text style={s.addText}>Add ingredient</Text></Pressable>
    <Pressable style={s.secondaryButton} onPress={()=>void createRecipe(duplicateRecipeInput(recipe)).then(copy=>router.replace({pathname:"/recipe-editor",params:{recipeId:copy.id}}))}><Text style={s.secondaryText}>Duplicate recipe</Text></Pressable>
    <Pressable style={s.secondaryButton} onPress={()=>Alert.alert("Delete recipe?","Logged diary entries will not be changed.",[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>void deleteRecipe(recipe.id).then(()=>router.back())}])}><Text style={s.remove}>Delete recipe</Text></Pressable>
  </ScrollView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:p.bg},center:{flex:1,alignItems:"center",justifyContent:"center",gap:16,backgroundColor:p.bg},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:20,paddingBottom:12},headerTitle:{fontSize:20,fontWeight:"700",color:p.label},done:{fontSize:17,fontWeight:"600",color:p.tint},content:{padding:16,gap:14},title:{fontSize:20,fontWeight:"700"},link:{fontSize:17,color:p.tint},nameInput:{fontSize:28,fontWeight:"700",color:p.label,backgroundColor:p.card,borderRadius:14,padding:16},card:{backgroundColor:p.card,borderRadius:14,paddingHorizontal:14},count:{fontSize:15,color:p.secondary,paddingTop:14},section:{fontSize:15,color:p.secondary,marginTop:4,paddingHorizontal:4},flex:{flex:1},itemRow:{minHeight:72,flexDirection:"row",alignItems:"center",gap:8,paddingVertical:12},itemName:{fontSize:17,color:p.label},meta:{fontSize:13,color:p.secondary,marginVertical:2},divider:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:p.separator},editor:{paddingBottom:14,gap:12},portions:{flexDirection:"row",gap:8},portionButton:{flex:1,alignItems:"center",paddingVertical:9,borderRadius:9,backgroundColor:p.bg},portionText:{color:p.tint,fontWeight:"700"},remove:{color:p.danger,fontSize:16,textAlign:"center"},empty:{paddingVertical:20,textAlign:"center",color:p.secondary},add:{minHeight:50,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6,borderRadius:14,backgroundColor:p.card},addText:{fontSize:17,fontWeight:"600",color:p.tint},secondaryButton:{minHeight:50,alignItems:"center",justifyContent:"center",borderRadius:14,backgroundColor:p.card},secondaryText:{fontSize:16,color:p.tint}});
