import { Platform, StyleSheet } from "react-native";
import { type AppTheme } from "../theme/useAppTheme";

export function createStyles({ palette }: AppTheme) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: palette.background,
    },
    contentContainer: {
      paddingHorizontal: 16,
    },
    scrollView: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.background,
    },
    loadingText: {
      fontSize: 16,
      color: palette.secondaryLabel,
    },
    largeTitle: {
      fontSize: 34,
      lineHeight: 41,
      fontWeight: "700",
      color: palette.label,
      paddingHorizontal: 4,
    },
    subtitle: {
      marginTop: 2,
      marginBottom: 14,
      paddingHorizontal: 4,
      fontSize: 15,
      lineHeight: 20,
      color: palette.secondaryLabel,
    },
    warningCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 14,
      marginBottom: 10,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.separator,
    },
    warningText: {
      color: palette.error,
      fontSize: 14,
      lineHeight: 19,
      fontWeight: "500",
    },
    emptyCard: {
      backgroundColor: palette.card,
      borderRadius: 16,
      padding: 20,
      marginTop: 8,
      marginBottom: 10,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.separator,
      alignItems: "center",
    },
    emptyText: {
      fontSize: 15,
      lineHeight: 21,
      color: palette.secondaryLabel,
      textAlign: "center",
    },
    messageBubble: {
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 6,
      maxWidth: "85%",
    },
    userBubble: {
      alignSelf: "flex-end",
      backgroundColor: palette.userBubble,
      borderBottomRightRadius: 6,
    },
    assistantBubble: {
      alignSelf: "flex-start",
      backgroundColor: palette.assistantBubble,
      borderBottomLeftRadius: 6,
    },
    searchBubble: {
      paddingHorizontal: 12,
      paddingVertical: 9,
      maxWidth: "92%",
      minWidth: 260,
    },
    searchSummaryRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    searchSummaryText: {
      flex: 1,
      fontSize: 14,
      lineHeight: 19,
      color: palette.secondaryLabel,
    },
    searchSummaryQuery: {
      color: palette.label,
      fontWeight: "600",
    },
    searchResultsClip: {
      overflow: "hidden",
    },
    searchResults: {
      marginTop: 9,
      paddingTop: 9,
      paddingBottom: 4,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: palette.separator,
      gap: 8,
    },
    searchResultRow: {
      gap: 4,
    },
    searchResultName: {
      fontSize: 14,
      lineHeight: 19,
      color: palette.label,
    },
    searchResultMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      flexWrap: "wrap",
    },
    searchResultMeta: {
      fontSize: 12,
      lineHeight: 16,
      color: palette.secondaryLabel,
    },
    audioBubble: {
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
      paddingVertical: 8,
      minWidth: 206,
    },
    audioIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.buttonText,
    },
    audioMetaColumn: {
      gap: 1,
    },
    audioLabel: {
      fontSize: 13,
      lineHeight: 16,
      fontWeight: "600",
    },
    audioDuration: {
      fontSize: 11,
      lineHeight: 14,
      fontVariant: ["tabular-nums"],
      color: "rgba(255,255,255,0.74)",
    },
    messageText: {
      fontSize: 16,
      lineHeight: 22,
      color: palette.label,
    },
    userMessageText: {
      color: palette.buttonText,
    },
    assistantMarkdown: {
      flex: 0,
      width: "100%",
      marginBottom: -12,
    },
    approvalBubble: {
      maxWidth: "92%",
      width: "92%",
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    toolCard: {
      borderRadius: 10,
      backgroundColor: palette.cardElevated,
      padding: 12,
      gap: 2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.separator,
    },
    suggestionCard: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: palette.separator,
    },
    toolTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    toolHeading: {
      fontSize: 13,
      lineHeight: 17,
      fontWeight: "700",
      color: palette.label,
    },
    toolText: {
      flex: 1,
      marginTop: 2,
      fontSize: 14,
      lineHeight: 19,
      color: palette.label,
    },
    toolMeta: {
      marginTop: 1,
      fontSize: 12,
      lineHeight: 17,
      color: palette.secondaryLabel,
    },
    toolMacroBadges: {
      marginTop: 6,
    },
    sourceBadge: {
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 999,
      overflow: "hidden",
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "700",
      color: palette.tint,
      backgroundColor: "rgba(37,99,235,0.12)",
    },
    toolReason: {
      marginTop: 8,
      fontSize: 13,
      lineHeight: 18,
      color: palette.secondaryLabel,
    },
    approvalRow: {
      marginTop: 12,
      flexDirection: "row",
      gap: 8,
      alignSelf: "stretch",
    },
    approveButton: {
      flex: 1,
      minWidth: 0,
      minHeight: 40,
      borderRadius: 10,
      backgroundColor: palette.success,
      alignItems: "center",
      justifyContent: "center",
    },
    approveButtonText: {
      color: palette.buttonText,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "600",
    },
    denyButton: {
      flex: 1,
      minWidth: 0,
      minHeight: 40,
      borderRadius: 10,
      backgroundColor: palette.error,
      alignItems: "center",
      justifyContent: "center",
    },
    denyButtonText: {
      color: palette.buttonText,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "600",
    },
    approvedText: {
      color: palette.success,
      fontWeight: "600",
    },
    rejectedText: {
      color: palette.error,
      fontWeight: "600",
    },
    errorText: {
      marginTop: 6,
      paddingHorizontal: 4,
      fontSize: 13,
      lineHeight: 18,
      color: palette.error,
    },
    errorCard: {
      marginBottom: 8,
    },
    errorDetailsText: {
      marginTop: 4,
      paddingHorizontal: 4,
      fontSize: 12,
      lineHeight: 17,
      color: palette.secondaryLabel,
      fontFamily: Platform.select({ ios: "Menlo", default: "monospace" }),
    },
    composerContainer: {
      paddingHorizontal: 12,
      paddingTop: 8,
      backgroundColor: palette.overlay,
      overflow: "visible",
    },
    composerRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 8,
      overflow: "visible",
    },
    inputBoxWrap: {
      flex: 1,
    },
    inputHost: {
      flex: 1,
      minHeight: 44,
    },
    inputGlass: {
      flex: 1,
      borderRadius: 22,
      paddingVertical: 6,
      paddingLeft: 16,
      paddingRight: 14,
      overflow: "hidden",
    },
    recordingCard: {
      flex: 1,
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: palette.cardElevated,
      borderRadius: 22,
      paddingVertical: 0,
      paddingLeft: 12,
      paddingRight: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.error,
    },
    recordingCardLocked: {
      paddingLeft: 10,
      backgroundColor: palette.cardElevated,
      borderColor: palette.error,
    },
    input: {
      minHeight: 36,
      maxHeight: 140,
      color: palette.label,
      paddingHorizontal: 0,
      paddingVertical: 8,
      fontSize: 16,
      lineHeight: 20,
    },
    sendButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    voiceSendButton: {
      backgroundColor: "transparent",
    },
    recordingStatusRow: {
      minWidth: 54,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    recordingLiveDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: palette.error,
    },
    recordingTimer: {
      color: palette.label,
      fontSize: 15,
      lineHeight: 20,
      fontVariant: ["tabular-nums"],
      fontWeight: "600",
    },
    recordingCancelHint: {
      width: 128,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 1,
    },
    recordingCancelHintText: {
      color: palette.secondaryLabel,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "500",
    },
    cancelRecordingButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    voiceActionWrap: {
      width: 44,
      height: 44,
      position: "relative",
      overflow: "visible",
      zIndex: 3,
    },
    voiceButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    voiceButtonRecording: {
      backgroundColor: "transparent",
    },
    recordingLockTarget: {
      position: "absolute",
      right: -10,
      bottom: 54,
      width: 64,
      height: 132,
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 5,
      paddingBottom: 2,
      zIndex: 4,
    },
    recordingLockBubble: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.cardElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.error,
    },
    recordingLockBubbleActive: {
      backgroundColor: palette.error,
    },
    recordingLockRail: {
      width: 4,
      height: 42,
      borderRadius: 2,
      backgroundColor: "rgba(127,127,127,0.20)",
      overflow: "hidden",
      justifyContent: "flex-end",
    },
    recordingLockRailFill: {
      width: 4,
      borderRadius: 2,
      backgroundColor: palette.error,
    },
    recordingLockHint: {
      color: palette.secondaryLabel,
      fontSize: 11,
      lineHeight: 13,
      fontWeight: "600",
      textAlign: "center",
    },
    buttonDisabled: {
      opacity: 0.4,
    },
  });
}

export type AIStyles = ReturnType<typeof createStyles>;
